export default {
  ReactJS: "ReactJS",
  MongoDB: "MongoDB",
  NodeJS: "NodeJS",
  PassportJS: "Passport",
  ExpressJS: "ExpressJS",
  CSS: "CSS",
  MaterialUI: "MaterialUI",
  JavaScript: "JavaScript",
  HTML: "HTML",
  Stripe: "Stripe",
  DragNDrop: "DragNDrop",
  HTTP_REST: "HTTP/REST",
  Cpp: "C++",
  Java: "Java",
};
